### PR TITLE
iTunes inspired theme

### PR DESCRIPTION
**Pull request by booploops**
Hello, I would actually like to submit 2 variations of the same theme if that is alright.  
This is a simple theme that modifies the window chrome to give the app more of a iTunes-esk look similar to High Sierra with some other small tweaks like a modern scrollbar (if enabled), fully draggable title bar, and a more macOS style back button.  I made two variations, one with a macOS appearance and the other Windows.  

I saw an enhancement request on the main Git page requesting a UWP style window frame so perhaps this could be a solution for that as well.

Screenshots: 
1 macOS Preview

2 Windows Preview

### CODE REVIEW

**Comment by coredev-uk** [comment]
YES!

**Comment by coredev-uk** [comment]
Great theme and the Window frame will serve as a great replacement for the ugly white bar that windows usually assigns the application when macOS app-emulation is disabled.

**Comment by coredev-uk** [comment]
@booploops To get the Windows frame working, did you disable the default frame?

**Comment by cryptofyre** [comment]
> @booploops To get the Windows frame working, did you disable the default frame?

They didn't

**Comment by booploops** [comment]
No, this is also using the Left (Default) macOS emu as well.  I'll include the visual settings from my config that I used for both.

`"visual": {
        "theme": "itunes_windows",
        "emulateMacOS": "left",
        "transparencyMode": [],
        "streamerMode": [],
        "removeUpsell": [
            true
        ],
        "removeFooter": [
            true
        ],
        "removeAppleLogo": [
            true
        ],
        "backButton": [
            true
        ],
        "transparencyEffect": "acrylic",
        "transparencyTheme": "appearance-based",
        "transparencyDisableBlur": [
            true
        ],
        "transparencyMaximumRefreshRate": "144"
    }`

**Pull request merged**
